Run of LISA Version 1.00; last modified 2/21/08

Note: Keith's ICARUS simulations from his email of 11/22/10
Note: (1) blizzard : snowflake :: army : soldier   (cross-domain, slow "true")
Note: (2) blizzard : snowflake :: monsoon : raindrop (within-domain, fast "true")
Note: (3) blizzard : snowflake :: tornado : cloud (false)
Note: (4) blizzard : snowflake :: truck : vehicle (far false)
Note: Approach is to use LISA's similarity engine to do this: Can analog MIP similarity serve as an index of analogy validity?
Note: This sym file implements analogy 4 above

* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *

Sequence:
Seq. 0    Driver:snow    Recip : truck    Fire control:props    Phase set: P1

Similarities as of step 0:
Similarity of snow to truck:
MOP Sim   = 0.019 
MIP Sim   = 0.393 
Total Sim = 0.411 
Similarity of truck to snow:
MOP Sim   = 0.019 
MIP Sim   = 0.393 
Total Sim = 0.411 



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From snow to truck:
  Groups:
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.2 = 0.993
    From SP1.2 to:    SP1.1 = 0.993
  Preds:
    From PART_OF1 to:    KIND_OF2 = 0.957
    From PART_OF2 to:    KIND_OF1 = 0.969
  Objs:
    From SNOWFLAKE to:    VEHICLE = 0.957
    From BLIZZARD to:    TRUCK = 0.969

From truck to snow:
  Groups:
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.2 = 0.993
    From SP1.2 to:    SP1.1 = 0.993
  Preds:
    From KIND_OF1 to:    PART_OF2 = 0.969
    From KIND_OF2 to:    PART_OF1 = 0.957
  Objs:
    From TRUCK to:    BLIZZARD = 0.969
    From VEHICLE to:    SNOWFLAKE = 0.957

