Note: GAT FTLD Task
Note: Distractor Condition: Normal subject
Note: Assume that Semantic Distractors share some predicate semantic units with
Note:  Assume perceptual distractors/Library/Frameworks/Python.framework/Versions/2.4/PyLISA2.4/VersBeta3/DATA/Bob/GatTask/distract2.bat share some object semantic unit overlap

* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.1000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 0.9000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *

Sequence:
Seq. 0    Driver:Problem    Recip : LTM    Fire control:props    Phase set: P1
Seq. 1    Driver:Problem    Recip : LTM    Fire control:props    Phase set: P1


* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From Problem to LTM:
  Preds:
    From RIGHT1 to:    RIGHT_B1 = 0.958
    From RIGHT2 to:    RIGHT_B2 = 0.958
  Objs:
    From A to:    C2 = 0.958
    From B to:    D2 = 0.958

From LTM to Problem:
  Preds:
    From RIGHT_A1 to:
    From RIGHT_A2 to:
    From RIGHT_B1 to:    RIGHT1 = 0.958
    From RIGHT_B2 to:    RIGHT2 = 0.958
    From RIGHT_C1 to:
    From RIGHT_C2 to:
    From RIGHT_D1 to:
    From RIGHT_D2 to:
    From WRONGS_A1 to:
    From WRONGS_A2 to:
    From WRONGS_B1 to:
    From WRONGS_B2 to:
    From WRONGS_C1 to:
    From WRONGS_C2 to:
    From WRONGS_D1 to:
    From WRONGS_D2 to:
    From WRONGP1 to:
    From WRONGP2 to:
  Objs:
    From C1 to:
    From C2 to:    A = 0.958
    From C3 to:
    From C4 to:
    From C5 to:
    From C6 to:
    From C7 to:
    From C8 to:
    From C9 to:
    From D1 to:
    From D2 to:    B = 0.958
    From D3 to:
    From D4 to:
    From S1 to:
    From S2 to:
    From S3 to:
    From S4 to:
    From P to:
    From U to:



* * * * * * * * * * * * * * * *
* * * * Inferred Units  * * * *
* * * * * * * * * * * * * * * *

* * * * * Analog Problem * * * * *

Groups:

Props:

Preds:

Objs:

* * * * * Analog LTM * * * * *

Groups:

Props:

Preds:

Objs:
