Note: GAT FTLD Task
Note: Distractor Condition
Note: Assume that Semantic Distractors share some predicate semantic units with
Note:  Assume perceptual distractors share some object semantic unit overlap

* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.3300
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 0.9000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *

Sequence:
Seq. 0    Driver:Problem    Recip : LTM    Fire control:props    Phase set: P1
Seq. 1    Driver:Problem    Recip : LTM    Fire control:props    Phase set: P1


* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From Problem to LTM:
  Groups:
  Props:
    From P1 to:    P2 = 0.981
  SPs:
    From SP1.1 to:    SP2.1 = 0.983
    From SP1.2 to:    SP2.2 = 0.983
  Preds:
    From RIGHT1 to:    WRONGS1 = 0.958
    From RIGHT2 to:    WRONGS2 = 0.958
  Objs:
    From A to:    C = 0.958
    From B to:    S = 0.958

From LTM to Problem:
  Groups:
  Props:
    From P1 to:
    From P2 to:    P1 = 0.981
    From P4 to:
    From P5 to:
  SPs:
    From SP1.1 to:
    From SP1.2 to:
    From SP2.1 to:    SP1.1 = 0.983
    From SP2.2 to:    SP1.2 = 0.983
    From SP4.1 to:
    From SP4.2 to:
    From SP5.1 to:
    From SP5.2 to:
  Preds:
    From RIGHT1 to:
    From RIGHT2 to:
    From WRONGS1 to:    RIGHT1 = 0.958
    From WRONGS2 to:    RIGHT2 = 0.958
    From WRONGP1 to:
    From WRONGP2 to:
    From WRONGU1 to:
    From WRONGU2 to:
  Objs:
    From C to:    A = 0.958
    From D to:
    From S to:    B = 0.958
    From P to:
    From U to:



* * * * * * * * * * * * * * * *
* * * * Inferred Units  * * * *
* * * * * * * * * * * * * * * *

* * * * * Analog Problem * * * * *

Groups:

Props:

Preds:

Objs:

* * * * * Analog LTM * * * * *

Groups:

Props:

Preds:

Objs:
