Run of LISA Version 1.00; last modified 10/18/11

Note: identity.sym
Note: Marcus's identity function in LISA

* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *

Sequence:
Seq. 0    Driver:Flower    Recip : One    Fire control:props    Phase set: P1
Seq. 1    Driver:One    Recip : Flower    Fire control:props    Phase set: P1
Seq. 2    Driver:One    Recip : Flower    Fire control:props    Phase set: P2


* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From One to Flower:
  Groups:
  Props:
    From P1 to:    P1 = 0.982
    From P2 to:    "P2" = 0.982
  SPs:
    From SP1.1 to:    SP1.1 = 0.992
    From SP2.1 to:    "SP2.1" = 0.987
  Preds:
    From IN1 to:    IN1 = 0.968
    From OUT1 to:    "OUT1" = 0.968
  Objs:
    From ONE to:    FLOWER = 0.968

From Flower to One:
  Groups:
  Props:
    From P1 to:    P1 = 0.982
    From "P2" to:    P2 = 0.982
  SPs:
    From SP1.1 to:    SP1.1 = 0.992
    From "SP2.1" to:    SP2.1 = 0.987
  Preds:
    From IN1 to:    IN1 = 0.968
    From "OUT1" to:    OUT1 = 0.968
  Objs:
    From FLOWER to:    ONE = 0.968



* * * * * * * * * * * * * * * *
* * * * Inferred Units  * * * *
* * * * * * * * * * * * * * * *

* * * * * Analog Flower * * * * *

Groups:

Props:
"P2":  [ "OUT1" + FLOWER ] 

Preds:
"OUT1":
   VARIABLE(1.000)
   OUTPUT(1.000)


Objs:
