
* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Unlimited WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = True
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *

Sequence:
Seq. 0    Driver:Boys    Recip : Dogs    Fire control:props    Phase set: P1 P2 P3 P4 P5
Seq. 1    Driver:Dogs    Recip : Boys    Fire control:props    Phase set: P1 P2 P3 P4 P5


* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From Boys to Dogs:
  Groups:
  Props:
    From P1 to:    P1 = 0.982
    From P2 to:    P5 = 0.982
    From P3 to:    P3 = 0.982
    From P4 to:    P4 = 0.982
    From P5 to:    P2 = 0.982
  SPs:
    From SP1.1 to:    SP1.1 = 0.987
    From SP2.1 to:    SP5.1 = 0.992
    From SP3.1 to:    SP3.1 = 0.992
    From SP4.1 to:    SP4.1 = 0.987
    From SP5.1 to:    SP2.1 = 0.992
  Preds:
    From SMART1 to:    HUNGRY1 = 0.982
    From TALL1 to:    FRIENDLY1 = 0.982
    From TIMID1 to:    FRISKY1 = 0.968
  Objs:
    From BILL to:    BLACKIE = 0.968
    From STEVE to:    FIDO = 0.968
    From TOM to:    ROVER = 0.968

From Dogs to Boys:
  Groups:
  Props:
    From P1 to:    P1 = 0.982
    From P2 to:    P5 = 0.982
    From P3 to:    P3 = 0.982
    From P4 to:    P4 = 0.982
    From P5 to:    P2 = 0.982
  SPs:
    From SP1.1 to:    SP1.1 = 0.987
    From SP2.1 to:    SP5.1 = 0.992
    From SP3.1 to:    SP3.1 = 0.992
    From SP4.1 to:    SP4.1 = 0.987
    From SP5.1 to:    SP2.1 = 0.992
  Preds:
    From HUNGRY1 to:    SMART1 = 0.982
    From FRIENDLY1 to:    TALL1 = 0.982
    From FRISKY1 to:    TIMID1 = 0.968
  Objs:
    From ROVER to:    TOM = 0.968
    From FIDO to:    STEVE = 0.968
    From BLACKIE to:    BILL = 0.968

