Run of LISA Version 1.00; last modified 7/24/07

Note: Lovetri2.sym the easy version of lovetri: no x-mapping
Note: This is an attempt to make a REAL sym file for MatLab LISA

* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *

Sequence:
Seq. 0    Driver:Abe&Beth    Recip : Amy&Bill    Fire control:props    Phase set: P1 P2
Seq. 1    Driver:Abe&Beth    Recip : Amy&Bill    Fire control:props    Phase set: P1 P2
Seq. 2    Driver:Abe&Beth    Recip : Amy&Bill    Fire control:props    Phase set: P1
Seq. 3    Driver:Abe&Beth    Recip : Amy&Bill    Fire control:props    Phase set: P2


* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From Amy&Bill to Abe&Beth:
  Groups:
    From G1 to:    G1 = 0.970
  Props:
    From P1 to:    P1 = 0.992
    From P2 to:    P2 = 0.992
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
    From SP2.1 to:    SP2.1 = 0.993
    From SP2.2 to:    SP2.2 = 0.993
  Preds:
    From LOVES1 to:    LOVES1 = 0.968
    From LOVES2 to:    LOVES2 = 0.968
  Objs:
    From AMY to:    ABE = 0.968
    From BILL to:    BETH = 0.968
    From CAT to:    CHAD = 0.968

From Abe&Beth to Amy&Bill:
  Groups:
    From G1 to:    G1 = 0.970
  Props:
    From P1 to:    P1 = 0.992
    From P2 to:    P2 = 0.992
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
    From SP2.1 to:    SP2.1 = 0.993
    From SP2.2 to:    SP2.2 = 0.993
  Preds:
    From LOVES1 to:    LOVES1 = 0.968
    From LOVES2 to:    LOVES2 = 0.968
  Objs:
    From ABE to:    AMY = 0.968
    From BETH to:    BILL = 0.968
    From CHAD to:    CAT = 0.968

